language: php
php:
#    - '5.6'
    - '7.0'
    - '7.1'

services:
    - mysql

before_install:
    - php /home/travis/.phpenv/versions/5.6/bin/composer self-update

#install:
#    - sudo apt-get install -y gdb # install gdb

before_script:
#    - ulimit -c unlimited -S # enable core dumps
    - composer install --no-interaction
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
    - php bin/console hautelook_alice:doctrine:fixtures:load -n --env=test

script:
    - phpunit --configuration phpunit.xml.dist --coverage-text

env:
    - ENV=test

#after_failure:
#    - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
#    - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi



#notifications:
#    email:
#        -  your@mail.here